name: Notificar en push a main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: 🔔 Se ha realizado un push o pull request" \
               -H "Priority: high" \
               -d "📦 Se han realizado cambios en el repositorio." \
               https://ntfy.sh/devops-itla
