name: notificar en push a main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
 notificar:
  runs-on: ubuntu-latest
  steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Se ha realiazo un push" \
               -H "Priority: high" \
               -d " Se hann realizados cambios en el repositorio " \
               https://ntfy.sh/devops-itla
  
